module.exports = {
  apps: [
    {
      name: 'lsc-orchestrator',
      cwd: '/var/www/html/lsc_marketing_automation/orchestrator',
      script: 'server.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      log_file: '/var/log/lsc/orchestrator.log',
      error_file: '/var/log/lsc/orchestrator-error.log',
      out_file: '/var/log/lsc/orchestrator-out.log',
      merge_logs: false,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'lsc-workers',
      cwd: '/var/www/html/lsc_marketing_automation/orchestrator',
      script: 'queues/worker-runner.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '768M',
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: '10s',
      log_file: '/var/log/lsc/workers.log',
      error_file: '/var/log/lsc/workers-error.log',
      out_file: '/var/log/lsc/workers-out.log',
      merge_logs: false,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'lsc-dashboard',
      cwd: '/var/www/html/lsc_marketing_automation/dashboard/.next/standalone',
      script: 'server.js',
      interpreter: 'node',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
        PORT: '4002',
        HOSTNAME: '127.0.0.1',
      },
      watch: false,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '384M',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
      log_file: '/var/log/lsc/dashboard.log',
      error_file: '/var/log/lsc/dashboard-error.log',
      out_file: '/var/log/lsc/dashboard-out.log',
      merge_logs: false,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'lsc-analytics',
      cwd: '/var/www/html/lsc_marketing_automation/api',
      script: 'uvicorn main:app --host 127.0.0.1 --port 8000 --workers 2',
      interpreter: 'bash',
      interpreter_args: '-c',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      max_memory_restart: '512M',
      restart_delay: 5000,
      max_restarts: 5,
      min_uptime: '10s',
      log_file: '/var/log/lsc/analytics.log',
      error_file: '/var/log/lsc/analytics-error.log',
      out_file: '/var/log/lsc/analytics-out.log',
      merge_logs: false,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
