module.exports = {
  apps: [
    {
      name: 'lsc-orchestrator',
      cwd: '/var/www/html/lsc_marketing_automation/orchestrator',
      script: 'server.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/lsc/orchestrator.log',
      error_file: '/var/log/lsc/orchestrator-error.log',
      out_file: '/var/log/lsc/orchestrator.log',
      merge_logs: true,
    },
    {
      name: 'lsc-workers',
      cwd: '/var/www/html/lsc_marketing_automation/orchestrator',
      script: 'queues/worker-runner.js',
      interpreter: 'node',
      interpreter_args: '--experimental-vm-modules',
      env_file: '/var/www/html/lsc_marketing_automation/.env',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/lsc/workers.log',
      error_file: '/var/log/lsc/workers-error.log',
      out_file: '/var/log/lsc/workers.log',
      merge_logs: true,
    },
    {
      name: 'lsc-dashboard',
      cwd: '/var/www/html/lsc_marketing_automation/dashboard',
      script: '.next/standalone/server.js',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: '4002',
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_API_URL: 'https://marketing.linkswitchcommunications.com',
        NEXTAUTH_URL: 'https://marketing.linkswitchcommunications.com',
        NEXTAUTH_SECRET: 'duNJn31ybi9dH6yuJFoQa3SFSFh/sGbguMakwIc+eos=',
        ADMIN_EMAIL: 'admin@lsc.local',
        ADMIN_PASSWORD: 'LSC@2026!',
      },
      watch: false,
      max_memory_restart: '256M',
      log_file: '/var/log/lsc/dashboard.log',
      error_file: '/var/log/lsc/dashboard-error.log',
      out_file: '/var/log/lsc/dashboard.log',
      merge_logs: true,
    },
  ],
};
